// templates/react/src/components/Message.js
import React, { Component } from "react";
import fetch from "node-fetch";

class Message extends Component {
  constructor() {
    super();

    this.state = {
      message: ""
    };
  }

  async componentDidMount() {
    if (!this.state.message) {
      let response = await fetch(`http://localhost:3001/message`);
      let json = await response.json();
      this.setState({ message: json.data });
    }
  }

  render() {
    return (
      <div>
        <h1>{this.state.message}</h1>
      </div>
    );
  }
}

export default Message;

// const wrapper = document.getElementById("container");
// // wrapper ? ReactDOM.render(<Form />, wrapper) : false;

// templates/vue/components/Message.vue
<template>
  <div>
    <h2>A secret message appears below...</h2>
    <br />
    <h3>{{ message }}</h3>
  </div>
</template>

<script>
import fetch from "node-fetch";
export default {
  data() {
    return { message: "" };
  },
  async mounted() {
    this.message = await this.makeRequest();
  },
  methods: {
    async makeRequest() {
      let response = await fetch(`http://localhost:3001/message`);
      let json = await response.json();
      return json.data;
    },
  },
};
</script>
